# -*- mode: ruby -*-
# vi: set ft=ruby :
hosts = {
  "n1" => "192.168.0.10",
  "n2" => "192.168.0.11",
  "n3" => "192.168.0.12",
  "n4" => "192.168.0.13"
}
Vagrant.configure("2") do |config|
  # всегда используем небезопасный ключ Vagrant
  config.ssh.insert_key = false
  # перенаправляем ssh-агент, чтобы получить легкий доступ к разным узлам
  config.ssh.forward_agent = true

  check_guest_additions = false
  functional_vboxsf = false

  config.vm.box = "bento/ubuntu-16.04"
hosts.each do |name, ip|
    config.vm.hostname = name
    config.vm.define name do |machine|
      machine.vm.network "public_network", ip: ip
      machine.vm.provider "virtualbox" do |v|
        v.name = name
	v.cpus = "2"
      end
    end
  end
end
